FROM python:3.8
# Need python <= 3.8: https://github.com/readthedocs/readthedocs.org/issues/9031

WORKDIR /app

COPY /back/requirements.txt ./
COPY /docs/requirements.txt ./requirements_docs.txt

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements_docs.txt

EXPOSE 8000

ENTRYPOINT ["tail", "-f", "/dev/null"]