FROM python:3.10

WORKDIR /app

COPY /back/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

# Copy all the backend files
# this assumes all the frontends are build and the static files have already been moved to ./back/static
ADD back /app/

EXPOSE 8000

CMD ["uvicorn", "back.asgi:application" ,"--port", "8000","--host", "0.0.0.0"]