FROM python:3.8
# Need python <= 3.8: https://github.com/readthedocs/readthedocs.org/issues/9031

WORKDIR /docs

COPY /back/requirements.txt ./
COPY /_docs/requirements.txt ./requirements_docs.txt


RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements_docs.txt

# We want the run file to be included in the docs
COPY ./run.py ./extra_mods/
RUN touch ./extra_mods/__init__.py
RUN touch ./__init__.py

EXPOSE 8000

ENTRYPOINT ["tail", "-f", "/dev/null"]