name: Run tests

on:
  push:
    branches: ['build-in-background']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  make_docs:
    runs-on: ubuntu-latest
    name: Build, checkut gh actions
    steps:
      - uses: actions/checkout@master
      - name: Build Image
        # We use '-b' to run the container in background
      shell: 'script -q -e -c "bash {0}"'
        run: python3 run.py -bg
      - name: Run Tests
        # Runns 'manage.py' test in the container
      shell: 'script -q -e -c "bash {0}"'
        run: python3 run.py ma -c test
